name: Follow-up Meeting
description: Utilisez ce modèle pour documenter une réunion de Suivi.
title: "[Réunion] Suivi - Date"
labels: ["meeting", "follow-up"]
body:
  - type: markdown
    attributes:
      value: |
        ## Participants
        - [ ] Nom (Rôle)
        - [ ] Nom (Rôle)

        ## Ordre du Jour
        - [ ] Progrès réalisés depuis la dernière réunion.
        - [ ] Points bloquants ou risques.
        - [ ] Ajustements nécessaires.

        ## Décisions
        - [ ] Décision 1.
        - [ ] Décision 2.

        ## Actions à Suivre
        - [ ] Action 1 : Responsable, Échéance
        - [ ] Action 2 : Responsable, Échéance

        ## Questions en Suspens
        - [ ] Question 1.
        - [ ] Question 2.
