name: Validation Meeting
description: Utilisez ce modèle pour documenter une réunion de Validation.
title: "[Réunion] Validation - Date"
labels: ["meeting", "validation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Participants
        - [ ] Nom (Rôle)
        - [ ] Nom (Rôle)

        ## Ordre du Jour
        - [ ] Présentation des livrables.
        - [ ] Vérification des critères d'acceptation.
        - [ ] Ajustements nécessaires.

        ## Décisions
        - [ ] Décision 1.
        - [ ] Décision 2.

        ## Actions à Suivre
        - [ ] Action 1 : Responsable, Échéance
        - [ ] Action 2 : Responsable, Échéance

        ## Questions en Suspens
        - [ ] Question 1.
        - [ ] Question 2.
