name: Validation Meeting
description: Template pour documenter une réunion de Validation.
title: "[Réunion] Validation - Date"
labels: ["meeting", "validation"]
body:
  - type: input
    id: participants
    attributes:
      label: "Participants"
      description: "Liste des participants avec leurs rôles"
      placeholder: "Exemple : Alice (Validateur), Bob (Développeur)"
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: "Livrables"
      description: "Liste des livrables présentés et leur état"
      placeholder: "Livrable 1 : Conforme\nLivrable 2 : Non conforme"

  - type: textarea
    id: decisions
    attributes:
      label: "Décisions"
      description: "Résumé des décisions prises pendant la réunion"
      placeholder: "Décision 1 : ...\nDécision 2 : ..."

  - type: textarea
    id: actions
    attributes:
      label: "Actions à Suivre"
      description: "Tâches définies avec responsables et échéances"
      placeholder: "Action 1 : Alice, échéance 2024-01-01\nAction 2 : Bob, échéance 2024-02-01"

  - type: textarea
    id: questions
    attributes:
      label: "Questions en Suspens"
      description: "Points ouverts nécessitant une action ultérieure"
      placeholder: "Question 1 : ...\nQuestion 2 : ..."
